language: php

php:
  # The adhocore/cron-expr should run fine with php 5.4+, but phpunit 5.7 requires php 5.6+
  # - 5.4
  # - 5.5
  - 5.6  
  - 7.0
  - 7.1

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text
